# Generated by Django 5.1.5 on 2025-03-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0005_order_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
    ]
