# Generated by Django 5.1.1 on 2025-03-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0007_order_payment_method_order_shipping_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
