# Generated by Django 5.1.1 on 2025-03-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0008_rename_status_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
    ]
