# Generated by Django 5.1.5 on 2025-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0009_rename_order_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
