# Generated by Django 5.1.5 on 2025-03-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0010_order_address_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
