# Generated by Django 5.1.5 on 2025-03-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0011_orderitem_product_name_orderitem_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_price',
        ),
    ]
