# Generated by Django 5.1.5 on 2025-03-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0012_remove_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_details',
        ),
    ]
