# Generated by Django 5.1.5 on 2025-03-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0014_coupon_order_discount_amount_order_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_from',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_to',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
