# Generated by Django 5.1.5 on 2025-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0015_rename_valid_from_coupon_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
