# Generated by Django 5.1.1 on 2025-03-23 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0016_coupon_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
