# Generated by Django 5.1.1 on 2025-03-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0017_alter_coupon_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
    ]
