# Generated by Django 5.1.1 on 2025-04-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0019_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_reason',
        ),
    ]
