# Generated by Django 5.1.1 on 2025-04-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0021_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
