# Generated by Django 5.1.1 on 2025-04-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0022_category_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
