# Generated by Django 5.1.1 on 2025-04-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0023_customuser_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_amount',
        ),
    ]
