# Generated by Django 5.1.5 on 2025-03-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_shippingconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingConfig',
        ),
    ]
