# Generated by Django 5.1.5 on 2025-03-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_delete_shippingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=10),
        ),
    ]
