# Generated by Django 5.1.1 on 2025-03-26 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0018_remove_order_razorpay_payment_id'),
        ('user_profile', '0008_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_complaints', to='auth_admin.order'),
        ),
    ]
