# Generated by Django 5.1.1 on 2025-03-26 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0018_remove_order_razorpay_payment_id'),
        ('user_profile', '0009_alter_complaint_options_alter_complaint_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='auth_admin.order'),
        ),
    ]
