# Generated by Django 5.1.1 on 2025-03-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0019_orderitem_status'),
        ('user_profile', '0010_alter_complaint_options_alter_complaint_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_admin.orderitem'),
            preserve_default=False,
        ),
    ]
