# Generated by Django 5.1.1 on 2025-03-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0019_orderitem_status'),
        ('user_profile', '0011_complaint_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='auth_admin.orderitem'),
        ),
    ]
