# Generated by Django 5.1.1 on 2025-03-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_complaint_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.AddField(
            model_name='complaint',
            name='status_complaint',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
